// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amswxkulhgtrmowocmtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtc3d4a3VsaGd0cm1vd29jbXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDMwNDIsImV4cCI6MjA2NTU3OTA0Mn0.f8nulNld9D1XGnqlLHDqG5Z2gDVTFqsnXdXWxsJ-OBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);